# Generated by Django 5.0.10 on 2025-01-10 04:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name_ru',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nomi RU'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name_uz',
            field=models.CharField(max_length=100, verbose_name='Nomi UZ'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.category', verbose_name='Kategoriya'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name_ru',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nomi RU'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name_uz',
            field=models.CharField(max_length=100, verbose_name='Nomi UZ'),
        ),
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=models.ImageField(upload_to='', verbose_name='Rasmi'),
        ),
        migrations.AlterField(
            model_name='product',
            name='photo_updated',
            field=models.BooleanField(default=False, editable=False, verbose_name='Rasm yangilandimi?'),
        ),
        migrations.AlterField(
            model_name='product',
            name='photo_uri',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True, verbose_name='Rasmi URI'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(verbose_name='Narxi'),
        ),
    ]
