# Generated by Django 5.0.10 on 2025-01-10 04:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Buyurtma', 'verbose_name_plural': 'Buyurtmalar'},
        ),
        migrations.AlterModelOptions(
            name='orderproduct',
            options={'verbose_name': 'Buyurtma maxsuloti', 'verbose_name_plural': 'Buyurtma maxsulotlari'},
        ),
        migrations.AlterField(
            model_name='order',
            name='cash_type',
            field=models.CharField(max_length=10, verbose_name="To'lov usuli"),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_address',
            field=models.CharField(max_length=255, verbose_name='Xaridor manzili'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_name',
            field=models.CharField(max_length=255, verbose_name='Xaridor ismi'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_phone',
            field=models.CharField(max_length=20, verbose_name='Xaridor raqami'),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order', verbose_name='Buyurtma'),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='product_count',
            field=models.IntegerField(default=1, verbose_name='Maxsulot soni'),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='product_name',
            field=models.CharField(max_length=255, verbose_name='Maxsulot nomi'),
        ),
    ]
