# Generated by Django 5.0.10 on 2025-01-26 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_options_alter_orderproduct_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_sum',
            field=models.CharField(default=1, max_length=10, verbose_name='Umumiy summa'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='total_price',
            field=models.IntegerField(default=1, verbose_name='Umumiy narx'),
            preserve_default=False,
        ),
    ]
