# Generated by Django 5.0.10 on 2025-01-26 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='customer_address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Xaridor manzili'),
        ),
    ]
