# Generated by Django 5.0.10 on 2025-01-26 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_order_customer_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cash_type',
            field=models.CharField(max_length=255, verbose_name="To'lov usuli"),
        ),
    ]
