# Generated by Django 5.0.10 on 2024-12-15 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_tguser'),
    ]

    operations = [
        migrations.AddField(
            model_name='tguser',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефонный номер'),
        ),
        migrations.AlterField(
            model_name='tguser',
            name='fullname',
            field=models.CharField(max_length=255, verbose_name='Полное имя'),
        ),
        migrations.AlterField(
            model_name='tguser',
            name='id',
            field=models.BigIntegerField(db_index=True, primary_key=True, serialize=False, unique=True, verbose_name='ID пользователя'),
        ),
        migrations.AlterField(
            model_name='tguser',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен?'),
        ),
        migrations.AlterField(
            model_name='tguser',
            name='username',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Имя пользователя'),
        ),
    ]
