# Generated by Django 5.0.10 on 2025-01-10 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_userlocations'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tguser',
            options={'verbose_name': 'Telegram foydalanuvchi', 'verbose_name_plural': 'Telegram foydalanuvchilar'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Admin foydalanuvchilar', 'verbose_name_plural': 'Admin foydalanuvchilar'},
        ),
        migrations.AlterModelOptions(
            name='userlocations',
            options={'verbose_name': 'Telegram lokatsiya', 'verbose_name_plural': 'Telegram lokatsiyalar'},
        ),
    ]
