# Generated by Django 5.0.10 on 2025-01-13 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_tguser_options_alter_user_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tguser',
            name='lang',
            field=models.CharField(default='uz', verbose_name='Язык пользователя'),
        ),
    ]
