# Generated by Django 5.0.10 on 2025-01-13 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_tguser_lang'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tguser',
            name='lang',
            field=models.CharField(default='uz', max_length=2, verbose_name='Язык пользователя'),
        ),
    ]
