# Generated by Django 5.0.10 on 2025-03-25 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_tguser_lang'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tguser',
            name='lang',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Язык пользователя'),
        ),
    ]
