# Generated by Django 5.0.10 on 2025-06-11 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_tguser_lang'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tguser',
            options={'verbose_name': 'Пользователь телеграм', 'verbose_name_plural': 'Пользователи телеграма'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Админ', 'verbose_name_plural': 'Админы'},
        ),
        migrations.RemoveField(
            model_name='tguser',
            name='lang',
        ),
        migrations.RemoveField(
            model_name='tguser',
            name='phone',
        ),
        migrations.AddField(
            model_name='tguser',
            name='age',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='tguser',
            name='education',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tguser',
            name='gender',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='tguser',
            name='location',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.DeleteModel(
            name='UserLocations',
        ),
    ]
