# Generated by Django 5.0.10 on 2025-06-19 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_tguser_options_alter_user_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tguser',
            name='age',
        ),
        migrations.RemoveField(
            model_name='tguser',
            name='education',
        ),
        migrations.RemoveField(
            model_name='tguser',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='tguser',
            name='location',
        ),
    ]
