# Generated by Django 5.0.10 on 2025-01-27 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_remove_tguser_age_remove_tguser_education_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tguser',
            name='last_activity',
            field=models.DateTimeField(auto_now=True, blank=True, null=True, verbose_name='Последняя активность'),
        ),
        migrations.AddField(
            model_name='tguser',
            name='blocked_bot',
            field=models.BooleanField(default=False, verbose_name='Заблокировал бота?'),
        ),
    ]
