# Generated by Django 5.0.10 on 2025-06-12 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'verbose_name': 'Ответ', 'verbose_name_plural': 'Ответы'},
        ),
        migrations.AlterModelOptions(
            name='choice',
            options={'verbose_name': 'Выбор', 'verbose_name_plural': 'Выборки'},
        ),
        migrations.AlterModelOptions(
            name='poll',
            options={'verbose_name': 'Тема', 'verbose_name_plural': 'Темы'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': 'Вопрос', 'verbose_name_plural': 'Вопросы'},
        ),
        migrations.AlterModelOptions(
            name='respondent',
            options={'verbose_name': 'Респондент', 'verbose_name_plural': 'Респонденты'},
        ),
    ]
