# Generated by Django 5.0.10 on 2025-06-22 04:02

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_alter_answer_options_alter_choice_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='respondent',
            name='history',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, size=None),
        ),
    ]
