# Generated by Django 5.0.10 on 2025-06-23 01:33

import markdownx.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_respondent_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='description',
            field=markdownx.models.MarkdownxField(),
        ),
    ]
