# Generated by Django 5.0.10 on 2025-07-13 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_alter_poll_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='is_answered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='answer',
            name='telegram_chat_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='answer',
            name='telegram_msg_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='answer',
            name='telegram_poll_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
