# Generated by Django 5.0.10 on 2025-07-22 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_answer_is_answered_answer_telegram_chat_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('closed_single', 'Закрытый — один ответ'), ('closed_multiple', 'Закрытый — несколько ответов'), ('open', 'Открытый'), ('mixed', 'Смешанный'), ('mixed_multiple', 'Смешанный — несколько ответов')], max_length=20),
        ),
    ]
