# Generated by Django 5.0.10 on 2025-08-11 05:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_exportfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_users', models.IntegerField(verbose_name='Общее количество пользователей')),
                ('sent_users', models.IntegerField(default=0, verbose_name='Отправлено пользователям')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Время начала')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Время завершения')),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('processing', 'В обработке'), ('completed', 'Завершено'), ('failed', 'Ошибка')], default='pending', max_length=20, verbose_name='Статус обработки')),
                ('error_message', models.TextField(blank=True, verbose_name='Сообщение об ошибке')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.poll', verbose_name='Тема')),
            ],
            options={
                'verbose_name': 'Кампания уведомлений',
                'verbose_name_plural': 'Кампании уведомлений',
                'ordering': ['-created_at'],
            },
        ),
    ]
