# Generated by Django 5.0.10 on 2025-09-05 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_notificationcampaign'),
    ]

    operations = [
        migrations.CreateModel(
            name='BroadcastPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок поста')),
                ('content', models.TextField(verbose_name='Содержание поста')),
                ('image', models.ImageField(blank=True, null=True, upload_to='broadcasts/', verbose_name='Изображение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('scheduled_at', models.DateTimeField(blank=True, null=True, verbose_name='Время отправки')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('scheduled', 'Запланировано'), ('sending', 'Отправляется'), ('sent', 'Отправлено'), ('failed', 'Ошибка')], default='draft', max_length=20, verbose_name='Статус')),
                ('total_users', models.IntegerField(default=0, verbose_name='Всего пользователей')),
                ('sent_users', models.IntegerField(default=0, verbose_name='Отправлено пользователям')),
                ('failed_users', models.IntegerField(default=0, verbose_name='Ошибок отправки')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Время начала отправки')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Время завершения')),
                ('error_message', models.TextField(blank=True, verbose_name='Сообщение об ошибке')),
            ],
            options={
                'verbose_name': 'Пост для рассылки',
                'verbose_name_plural': 'Посты для рассылки',
                'ordering': ['-created_at'],
            },
        ),
    ]
