# Generated by Django 5.0.10 on 2025-09-12 10:40

import apps.polls.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0013_set_null_total_users_to_zero'),
    ]

    operations = [
        migrations.AddField(
            model_name='exportfile',
            name='chunk_size',
            field=models.PositiveIntegerField(default=1000, verbose_name='Размер части'),
        ),
        migrations.AddField(
            model_name='exportfile',
            name='completed_chunks',
            field=models.PositiveIntegerField(default=0, verbose_name='Завершенных частей'),
        ),
        migrations.AddField(
            model_name='exportfile',
            name='is_chunked',
            field=models.BooleanField(default=False, verbose_name='Разделен на части'),
        ),
        migrations.AddField(
            model_name='exportfile',
            name='total_chunks',
            field=models.PositiveIntegerField(default=1, verbose_name='Общее количество частей'),
        ),
        migrations.CreateModel(
            name='ExportChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunk_number', models.PositiveIntegerField(verbose_name='Номер части')),
                ('file', models.FileField(blank=True, null=True, upload_to=apps.polls.models.export_file_path, verbose_name='Файл части')),
                ('filename', models.CharField(max_length=255, verbose_name='Имя файла части')),
                ('status', models.CharField(choices=[('pending', 'В ожидании'), ('processing', 'Обрабатывается'), ('completed', 'Завершено'), ('failed', 'Ошибка')], default='pending', max_length=20, verbose_name='Статус')),
                ('rows_count', models.PositiveIntegerField(default=0, verbose_name='Количество строк')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата завершения')),
                ('error_message', models.TextField(blank=True, verbose_name='Сообщение об ошибке')),
                ('export_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='polls.exportfile', verbose_name='Основной экспорт')),
            ],
            options={
                'verbose_name': 'Часть экспорта',
                'verbose_name_plural': 'Части экспорта',
                'ordering': ['export_file', 'chunk_number'],
                'unique_together': {('export_file', 'chunk_number')},
            },
        ),
    ]
